# Generated by Django 4.0.4 on 2022-06-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_login_registeration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Loginn',
        ),
        migrations.RenameModel(
            old_name='Registeration',
            new_name='Register',
        ),
    ]
