# Generated by Django 4.0.4 on 2022-06-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_rename_login_loginn_rename_registeration_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Sname',
        ),
    ]
