# Generated by Django 4.0.4 on 2022-06-29 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_library_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='authorName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
